name: "Release: docker"

on:
  schedule:
    - cron: '0 6 * * 1'
  push:
    branches:
      - '**'
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: webdevops/azure-scheduledevents-manager,quay.io/webdevops/azure-scheduledevents-manager
          tag-latest: true
          tag-semver: |-
            {{raw}}
          tag-schedule: nightly
